dist: trusty
sudo: required
language: java
jdk: oraclejdk8

env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"

script:
  - ./mvn clean test
  - ./mvn verify

deploy:
  provider: cloudfoundry
  api: $CF_API_URL
  username: $CF_USERNAME
  password: $CF_PASSWORD
  organization: $CF_ORG
  space: $CF_SPACE